### ISSUE TITLE
Migration message keeps appearing

### ISSUE THREAD

**Issue by operatorone** [oveleon/contao-component-style-manager#84]
After installation, the message "StyleManager configurations were successfully converted. Please note, if custom tables have been added to the StyleManager, they must be migrated using the `contao:stylemanager:object-conversion table` command." keeps appearing in the Contao Manager or the Install tool. No custom tables used.

**Comment by zoglo** [comment]
@operatorone you can circument this by creating a stylemanager archive and an item and running the migration again.

I've seen this bug reappear a few times but I was not able to reproduce it.
According to @doishub it was fixed a while ago.

Could you leave more information and what exactly you did? Just a new installation?

**Comment by operatorone** [comment]
I'll try your workaround. 

Here is what I did: I just updated a 2.* installation in the manager by typing 3.* in the version field and ran an update. I executed the migration in the migration section afterwards. Unfortunately, the message blocks all other queries in the migration tool, so when I installed another extension I had to use the install tool (I'm happy that it's still there). I could execute my queries, but the message remains visible.

**Comment by operatorone** [comment]
By "add a new archive" you meant a category? I added a new one and tried to migrate. Message is still appearing.

https://share.cleanshot.com/kjFmQcKxbxgHXNfmlk1W

**Comment by zoglo** [comment]
Hey @operatorone

I've messaged you via email if you could send me a dump of your following tables
- tl_style_manager
- tl_style_manager_archive
- tl_article
- tl_content

Without those, I won't be able to reproduce the issue.

It seems as if there is some migrations that fail due to installing the StyleManager in version 3 and afterwards migrating a database dump into your installation.

**Comment by operatorone** [comment]
No  problem. Where to send to?

**Comment by operatorone** [comment]
Ah , found your mail in the spam ;-) Will answer.

**Comment by zoglo** [comment]
After research and talks with operatorone, we've found out that this issue appears cause they did migrate the StyleManager to version 3.x already and tried to import a dump with content-elements, modules, etc. that had old stylemanager options.

The right way to do it would be following:
- use a dump that has never been migrated
- update from v2 to v3
- let the migration happen

I could not reproduce the issue at all.

What you could do is to either follow the correct update order or:
- delete the stylemanager field for tl_form / tl_form_field and other affected tables
